// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logic

import (
	"context"
	"github.com/harryv2/ryuk-dpq/backend/config"
	"github.com/harryv2/ryuk-dpq/backend/gateway/repo/membershipetcd"
	"github.com/harryv2/ryuk-dpq/backend/gateway/repo/nodegrpc"
	"github.com/harryv2/ryuk-dpq/backend/gateway/repo/postgres"
	"github.com/harryv2/ryuk-dpq/backend/gateway/repo/prometheus"
)

// Injectors from container.go:

// InitialiseGatewayLogic builds the god struct and everything under it. Swapping
// an implementation is one wire.Bind line.
func InitialiseGatewayLogic(ctx context.Context, cfg config.Gateway) (*GatewayLogic, func(), error) {
	logicConfig := ProvideConfig(cfg)
	logger := ProvideLogger(cfg)
	dsn := ProvidePostgresDSN(cfg)
	dbWrapper, cleanup, err := postgres.NewDBWrapper(ctx, dsn)
	if err != nil {
		return nil, nil, err
	}
	queuesTable := postgres.NewQueuesTable(dbWrapper)
	slotPlacementTable := postgres.NewSlotPlacementTable(dbWrapper)
	repo := nodegrpc.New()
	endpoints := ProvideEtcdEndpoints(cfg)
	membershipetcdRepo, cleanup2, err := membershipetcd.New(endpoints, logger)
	if err != nil {
		cleanup()
		return nil, nil, err
	}
	baseURL := ProvidePrometheusURL(cfg)
	prometheusRepo := prometheus.New(baseURL, logger)
	gatewayLogic := New(logicConfig, logger, queuesTable, slotPlacementTable, repo, membershipetcdRepo, prometheusRepo)
	return gatewayLogic, func() {
		cleanup2()
		cleanup()
	}, nil
}
