// Code generated by MockGen. DO NOT EDIT.
// Source: backend/gateway/entity/repo-table-queue.go
//
// Generated by this command:
//
//	mockgen -source=backend/gateway/entity/repo-table-queue.go -destination=backend/gateway/mocks/mock_queue_table_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/harryv2/ryuk-dpq/backend/gateway/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockQueueTableRepo is a mock of QueueTableRepo interface.
type MockQueueTableRepo struct {
	ctrl     *gomock.Controller
	recorder *MockQueueTableRepoMockRecorder
	isgomock struct{}
}

// MockQueueTableRepoMockRecorder is the mock recorder for MockQueueTableRepo.
type MockQueueTableRepoMockRecorder struct {
	mock *MockQueueTableRepo
}

// NewMockQueueTableRepo creates a new mock instance.
func NewMockQueueTableRepo(ctrl *gomock.Controller) *MockQueueTableRepo {
	mock := &MockQueueTableRepo{ctrl: ctrl}
	mock.recorder = &MockQueueTableRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockQueueTableRepo) EXPECT() *MockQueueTableRepoMockRecorder {
	return m.recorder
}

// Create mocks base method.
func (m *MockQueueTableRepo) Create(ctx context.Context, cfg entity.QueueConfig) (entity.QueueConfig, bool, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Create", ctx, cfg)
	ret0, _ := ret[0].(entity.QueueConfig)
	ret1, _ := ret[1].(bool)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// Create indicates an expected call of Create.
func (mr *MockQueueTableRepoMockRecorder) Create(ctx, cfg any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Create", reflect.TypeOf((*MockQueueTableRepo)(nil).Create), ctx, cfg)
}

// Delete mocks base method.
func (m *MockQueueTableRepo) Delete(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Delete", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// Delete indicates an expected call of Delete.
func (mr *MockQueueTableRepoMockRecorder) Delete(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Delete", reflect.TypeOf((*MockQueueTableRepo)(nil).Delete), ctx, org, name)
}

// Get mocks base method.
func (m *MockQueueTableRepo) Get(ctx context.Context, org, name string) (entity.QueueConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Get", ctx, org, name)
	ret0, _ := ret[0].(entity.QueueConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Get indicates an expected call of Get.
func (mr *MockQueueTableRepoMockRecorder) Get(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Get", reflect.TypeOf((*MockQueueTableRepo)(nil).Get), ctx, org, name)
}

// ListAll mocks base method.
func (m *MockQueueTableRepo) ListAll(ctx context.Context) ([]entity.QueueConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListAll", ctx)
	ret0, _ := ret[0].([]entity.QueueConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListAll indicates an expected call of ListAll.
func (mr *MockQueueTableRepoMockRecorder) ListAll(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListAll", reflect.TypeOf((*MockQueueTableRepo)(nil).ListAll), ctx)
}

// ListByOrg mocks base method.
func (m *MockQueueTableRepo) ListByOrg(ctx context.Context, org string) ([]entity.QueueConfig, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByOrg", ctx, org)
	ret0, _ := ret[0].([]entity.QueueConfig)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByOrg indicates an expected call of ListByOrg.
func (mr *MockQueueTableRepoMockRecorder) ListByOrg(ctx, org any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByOrg", reflect.TypeOf((*MockQueueTableRepo)(nil).ListByOrg), ctx, org)
}

// SetOwner mocks base method.
func (m *MockQueueTableRepo) SetOwner(ctx context.Context, org, name, owner string, generation uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOwner", ctx, org, name, owner, generation)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOwner indicates an expected call of SetOwner.
func (mr *MockQueueTableRepoMockRecorder) SetOwner(ctx, org, name, owner, generation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwner", reflect.TypeOf((*MockQueueTableRepo)(nil).SetOwner), ctx, org, name, owner, generation)
}

// SetState mocks base method.
func (m *MockQueueTableRepo) SetState(ctx context.Context, org, name string, state entity.QueueState) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetState", ctx, org, name, state)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetState indicates an expected call of SetState.
func (mr *MockQueueTableRepoMockRecorder) SetState(ctx, org, name, state any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetState", reflect.TypeOf((*MockQueueTableRepo)(nil).SetState), ctx, org, name, state)
}

// UpdateSettings mocks base method.
func (m *MockQueueTableRepo) UpdateSettings(ctx context.Context, org, name string, s entity.QueueSettings) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "UpdateSettings", ctx, org, name, s)
	ret0, _ := ret[0].(error)
	return ret0
}

// UpdateSettings indicates an expected call of UpdateSettings.
func (mr *MockQueueTableRepoMockRecorder) UpdateSettings(ctx, org, name, s any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "UpdateSettings", reflect.TypeOf((*MockQueueTableRepo)(nil).UpdateSettings), ctx, org, name, s)
}
