// Code generated by MockGen. DO NOT EDIT.
// Source: backend/gateway/entity/repo-timeseries.go
//
// Generated by this command:
//
//	mockgen -source=backend/gateway/entity/repo-timeseries.go -destination=backend/gateway/mocks/mock_timeseries_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/harryv2/ryuk-dpq/backend/gateway/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockTimeseriesRepo is a mock of TimeseriesRepo interface.
type MockTimeseriesRepo struct {
	ctrl     *gomock.Controller
	recorder *MockTimeseriesRepoMockRecorder
	isgomock struct{}
}

// MockTimeseriesRepoMockRecorder is the mock recorder for MockTimeseriesRepo.
type MockTimeseriesRepoMockRecorder struct {
	mock *MockTimeseriesRepo
}

// NewMockTimeseriesRepo creates a new mock instance.
func NewMockTimeseriesRepo(ctrl *gomock.Controller) *MockTimeseriesRepo {
	mock := &MockTimeseriesRepo{ctrl: ctrl}
	mock.recorder = &MockTimeseriesRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockTimeseriesRepo) EXPECT() *MockTimeseriesRepoMockRecorder {
	return m.recorder
}

// Query mocks base method.
func (m *MockTimeseriesRepo) Query(ctx context.Context, q entity.TimeseriesQuery) (entity.TimeseriesResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Query", ctx, q)
	ret0, _ := ret[0].(entity.TimeseriesResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Query indicates an expected call of Query.
func (mr *MockTimeseriesRepoMockRecorder) Query(ctx, q any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Query", reflect.TypeOf((*MockTimeseriesRepo)(nil).Query), ctx, q)
}

// Ready mocks base method.
func (m *MockTimeseriesRepo) Ready(ctx context.Context) bool {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ready", ctx)
	ret0, _ := ret[0].(bool)
	return ret0
}

// Ready indicates an expected call of Ready.
func (mr *MockTimeseriesRepoMockRecorder) Ready(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ready", reflect.TypeOf((*MockTimeseriesRepo)(nil).Ready), ctx)
}
