// Code generated by MockGen. DO NOT EDIT.
// Source: backend/gateway/entity/repo-table-slot-placement.go
//
// Generated by this command:
//
//	mockgen -source=backend/gateway/entity/repo-table-slot-placement.go -destination=backend/gateway/mocks/mock_slot_placement_table_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockSlotPlacementTableRepo is a mock of SlotPlacementTableRepo interface.
type MockSlotPlacementTableRepo struct {
	ctrl     *gomock.Controller
	recorder *MockSlotPlacementTableRepoMockRecorder
	isgomock struct{}
}

// MockSlotPlacementTableRepoMockRecorder is the mock recorder for MockSlotPlacementTableRepo.
type MockSlotPlacementTableRepoMockRecorder struct {
	mock *MockSlotPlacementTableRepo
}

// NewMockSlotPlacementTableRepo creates a new mock instance.
func NewMockSlotPlacementTableRepo(ctrl *gomock.Controller) *MockSlotPlacementTableRepo {
	mock := &MockSlotPlacementTableRepo{ctrl: ctrl}
	mock.recorder = &MockSlotPlacementTableRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockSlotPlacementTableRepo) EXPECT() *MockSlotPlacementTableRepoMockRecorder {
	return m.recorder
}

// DeleteByQueue mocks base method.
func (m *MockSlotPlacementTableRepo) DeleteByQueue(ctx context.Context, org, name string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeleteByQueue", ctx, org, name)
	ret0, _ := ret[0].(error)
	return ret0
}

// DeleteByQueue indicates an expected call of DeleteByQueue.
func (mr *MockSlotPlacementTableRepoMockRecorder) DeleteByQueue(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeleteByQueue", reflect.TypeOf((*MockSlotPlacementTableRepo)(nil).DeleteByQueue), ctx, org, name)
}

// ListByQueue mocks base method.
func (m *MockSlotPlacementTableRepo) ListByQueue(ctx context.Context, org, name string) (map[uint16]string, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "ListByQueue", ctx, org, name)
	ret0, _ := ret[0].(map[uint16]string)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// ListByQueue indicates an expected call of ListByQueue.
func (mr *MockSlotPlacementTableRepoMockRecorder) ListByQueue(ctx, org, name any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "ListByQueue", reflect.TypeOf((*MockSlotPlacementTableRepo)(nil).ListByQueue), ctx, org, name)
}

// SetOwner mocks base method.
func (m *MockSlotPlacementTableRepo) SetOwner(ctx context.Context, org, name string, slot uint16, owner string, generation uint64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "SetOwner", ctx, org, name, slot, owner, generation)
	ret0, _ := ret[0].(error)
	return ret0
}

// SetOwner indicates an expected call of SetOwner.
func (mr *MockSlotPlacementTableRepoMockRecorder) SetOwner(ctx, org, name, slot, owner, generation any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "SetOwner", reflect.TypeOf((*MockSlotPlacementTableRepo)(nil).SetOwner), ctx, org, name, slot, owner, generation)
}
