// Code generated by MockGen. DO NOT EDIT.
// Source: backend/gateway/entity/repo-node.go
//
// Generated by this command:
//
//	mockgen -source=backend/gateway/entity/repo-node.go -destination=backend/gateway/mocks/mock_node_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/harryv2/ryuk-dpq/backend/gateway/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNodeRepo is a mock of NodeRepo interface.
type MockNodeRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNodeRepoMockRecorder
	isgomock struct{}
}

// MockNodeRepoMockRecorder is the mock recorder for MockNodeRepo.
type MockNodeRepoMockRecorder struct {
	mock *MockNodeRepo
}

// NewMockNodeRepo creates a new mock instance.
func NewMockNodeRepo(ctrl *gomock.Controller) *MockNodeRepo {
	mock := &MockNodeRepo{ctrl: ctrl}
	mock.recorder = &MockNodeRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeRepo) EXPECT() *MockNodeRepoMockRecorder {
	return m.recorder
}

// Absorb mocks base method.
func (m *MockNodeRepo) Absorb(ctx context.Context, addr string, t entity.Transfer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Absorb", ctx, addr, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Absorb indicates an expected call of Absorb.
func (mr *MockNodeRepoMockRecorder) Absorb(ctx, addr, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Absorb", reflect.TypeOf((*MockNodeRepo)(nil).Absorb), ctx, addr, t)
}

// Ack mocks base method.
func (m *MockNodeRepo) Ack(ctx context.Context, addr string, spec entity.QueueSpec, receipt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, addr, spec, receipt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockNodeRepoMockRecorder) Ack(ctx, addr, spec, receipt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockNodeRepo)(nil).Ack), ctx, addr, spec, receipt)
}

// Dequeue mocks base method.
func (m *MockNodeRepo) Dequeue(ctx context.Context, addr string, spec entity.QueueSpec, max int) ([]entity.NodeMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dequeue", ctx, addr, spec, max)
	ret0, _ := ret[0].([]entity.NodeMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dequeue indicates an expected call of Dequeue.
func (mr *MockNodeRepoMockRecorder) Dequeue(ctx, addr, spec, max any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dequeue", reflect.TypeOf((*MockNodeRepo)(nil).Dequeue), ctx, addr, spec, max)
}

// Drop mocks base method.
func (m *MockNodeRepo) Drop(ctx context.Context, addr string, spec entity.QueueSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drop", ctx, addr, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Drop indicates an expected call of Drop.
func (mr *MockNodeRepoMockRecorder) Drop(ctx, addr, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockNodeRepo)(nil).Drop), ctx, addr, spec)
}

// Enqueue mocks base method.
func (m *MockNodeRepo) Enqueue(ctx context.Context, addr string, req entity.NodeEnqueue) (entity.NodeEnqueueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, addr, req)
	ret0, _ := ret[0].(entity.NodeEnqueueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockNodeRepoMockRecorder) Enqueue(ctx, addr, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockNodeRepo)(nil).Enqueue), ctx, addr, req)
}

// Freeze mocks base method.
func (m *MockNodeRepo) Freeze(ctx context.Context, addr string, spec entity.QueueSpec, slots []uint16) (entity.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Freeze", ctx, addr, spec, slots)
	ret0, _ := ret[0].(entity.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Freeze indicates an expected call of Freeze.
func (mr *MockNodeRepoMockRecorder) Freeze(ctx, addr, spec, slots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Freeze", reflect.TypeOf((*MockNodeRepo)(nil).Freeze), ctx, addr, spec, slots)
}

// Nack mocks base method.
func (m *MockNodeRepo) Nack(ctx context.Context, addr string, spec entity.QueueSpec, receipt string, delay time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nack", ctx, addr, spec, receipt, delay)
	ret0, _ := ret[0].(error)
	return ret0
}

// Nack indicates an expected call of Nack.
func (mr *MockNodeRepoMockRecorder) Nack(ctx, addr, spec, receipt, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nack", reflect.TypeOf((*MockNodeRepo)(nil).Nack), ctx, addr, spec, receipt, delay)
}

// Stats mocks base method.
func (m *MockNodeRepo) Stats(ctx context.Context, addr string, spec entity.QueueSpec) (entity.NodeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, addr, spec)
	ret0, _ := ret[0].(entity.NodeStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockNodeRepoMockRecorder) Stats(ctx, addr, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockNodeRepo)(nil).Stats), ctx, addr, spec)
}

// StatsAll mocks base method.
func (m *MockNodeRepo) StatsAll(ctx context.Context, addr string) (string, []entity.NodeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatsAll", ctx, addr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]entity.NodeStats)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StatsAll indicates an expected call of StatsAll.
func (mr *MockNodeRepoMockRecorder) StatsAll(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatsAll", reflect.TypeOf((*MockNodeRepo)(nil).StatsAll), ctx, addr)
}

// Subscribe mocks base method.
func (m *MockNodeRepo) Subscribe(ctx context.Context, addr, gatewayID string) (<-chan entity.WorkAvailable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, addr, gatewayID)
	ret0, _ := ret[0].(<-chan entity.WorkAvailable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNodeRepoMockRecorder) Subscribe(ctx, addr, gatewayID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNodeRepo)(nil).Subscribe), ctx, addr, gatewayID)
}
