// Code generated by MockGen. DO NOT EDIT.
// Source: backend/gateway/entity/repo-membership.go
//
// Generated by this command:
//
//	mockgen -source=backend/gateway/entity/repo-membership.go -destination=backend/gateway/mocks/mock_membership_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	entity "github.com/harryv2/ryuk-dpq/backend/gateway/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockMembershipRepo is a mock of MembershipRepo interface.
type MockMembershipRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepoMockRecorder
	isgomock struct{}
}

// MockMembershipRepoMockRecorder is the mock recorder for MockMembershipRepo.
type MockMembershipRepoMockRecorder struct {
	mock *MockMembershipRepo
}

// NewMockMembershipRepo creates a new mock instance.
func NewMockMembershipRepo(ctrl *gomock.Controller) *MockMembershipRepo {
	mock := &MockMembershipRepo{ctrl: ctrl}
	mock.recorder = &MockMembershipRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepo) EXPECT() *MockMembershipRepoMockRecorder {
	return m.recorder
}

// Changed mocks base method.
func (m *MockMembershipRepo) Changed() <-chan struct{} {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Changed")
	ret0, _ := ret[0].(<-chan struct{})
	return ret0
}

// Changed indicates an expected call of Changed.
func (mr *MockMembershipRepoMockRecorder) Changed() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Changed", reflect.TypeOf((*MockMembershipRepo)(nil).Changed))
}

// Lookup mocks base method.
func (m *MockMembershipRepo) Lookup(id string) (entity.Member, bool) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Lookup", id)
	ret0, _ := ret[0].(entity.Member)
	ret1, _ := ret[1].(bool)
	return ret0, ret1
}

// Lookup indicates an expected call of Lookup.
func (mr *MockMembershipRepoMockRecorder) Lookup(id any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Lookup", reflect.TypeOf((*MockMembershipRepo)(nil).Lookup), id)
}

// Members mocks base method.
func (m *MockMembershipRepo) Members() []entity.Member {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Members")
	ret0, _ := ret[0].([]entity.Member)
	return ret0
}

// Members indicates an expected call of Members.
func (mr *MockMembershipRepoMockRecorder) Members() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Members", reflect.TypeOf((*MockMembershipRepo)(nil).Members))
}

// Watch mocks base method.
func (m *MockMembershipRepo) Watch(ctx context.Context) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Watch", ctx)
	ret0, _ := ret[0].(error)
	return ret0
}

// Watch indicates an expected call of Watch.
func (mr *MockMembershipRepoMockRecorder) Watch(ctx any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Watch", reflect.TypeOf((*MockMembershipRepo)(nil).Watch), ctx)
}
