// Code generated by MockGen. DO NOT EDIT.
// Source: backend/gateway/entity/repo-node.go
//
// Generated by this command:
//
//	mockgen -source=backend/gateway/entity/repo-node.go -destination=backend/gateway/mocks/mock_node_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"
	time "time"

	entity "github.com/harryv2/ryuk-dpq/backend/gateway/entity"
	gomock "go.uber.org/mock/gomock"
)

// MockNodeGRPCRepo is a mock of NodeGRPCRepo interface.
type MockNodeGRPCRepo struct {
	ctrl     *gomock.Controller
	recorder *MockNodeGRPCRepoMockRecorder
	isgomock struct{}
}

// MockNodeGRPCRepoMockRecorder is the mock recorder for MockNodeGRPCRepo.
type MockNodeGRPCRepoMockRecorder struct {
	mock *MockNodeGRPCRepo
}

// NewMockNodeGRPCRepo creates a new mock instance.
func NewMockNodeGRPCRepo(ctrl *gomock.Controller) *MockNodeGRPCRepo {
	mock := &MockNodeGRPCRepo{ctrl: ctrl}
	mock.recorder = &MockNodeGRPCRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockNodeGRPCRepo) EXPECT() *MockNodeGRPCRepoMockRecorder {
	return m.recorder
}

// AbortMove mocks base method.
func (m *MockNodeGRPCRepo) AbortMove(ctx context.Context, addr string, spec entity.QueueSpec, slots []uint16, moveID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AbortMove", ctx, addr, spec, slots, moveID)
	ret0, _ := ret[0].(error)
	return ret0
}

// AbortMove indicates an expected call of AbortMove.
func (mr *MockNodeGRPCRepoMockRecorder) AbortMove(ctx, addr, spec, slots, moveID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AbortMove", reflect.TypeOf((*MockNodeGRPCRepo)(nil).AbortMove), ctx, addr, spec, slots, moveID)
}

// Absorb mocks base method.
func (m *MockNodeGRPCRepo) Absorb(ctx context.Context, addr string, t entity.Transfer) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Absorb", ctx, addr, t)
	ret0, _ := ret[0].(error)
	return ret0
}

// Absorb indicates an expected call of Absorb.
func (mr *MockNodeGRPCRepoMockRecorder) Absorb(ctx, addr, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Absorb", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Absorb), ctx, addr, t)
}

// Ack mocks base method.
func (m *MockNodeGRPCRepo) Ack(ctx context.Context, addr string, spec entity.QueueSpec, receipt string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Ack", ctx, addr, spec, receipt)
	ret0, _ := ret[0].(error)
	return ret0
}

// Ack indicates an expected call of Ack.
func (mr *MockNodeGRPCRepoMockRecorder) Ack(ctx, addr, spec, receipt any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Ack", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Ack), ctx, addr, spec, receipt)
}

// AckDeadLetters mocks base method.
func (m *MockNodeGRPCRepo) AckDeadLetters(ctx context.Context, addr string, ids []string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "AckDeadLetters", ctx, addr, ids)
	ret0, _ := ret[0].(error)
	return ret0
}

// AckDeadLetters indicates an expected call of AckDeadLetters.
func (mr *MockNodeGRPCRepoMockRecorder) AckDeadLetters(ctx, addr, ids any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AckDeadLetters", reflect.TypeOf((*MockNodeGRPCRepo)(nil).AckDeadLetters), ctx, addr, ids)
}

// DeadLetters mocks base method.
func (m *MockNodeGRPCRepo) DeadLetters(ctx context.Context, addr string) ([]entity.DeadLetterItem, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DeadLetters", ctx, addr)
	ret0, _ := ret[0].([]entity.DeadLetterItem)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// DeadLetters indicates an expected call of DeadLetters.
func (mr *MockNodeGRPCRepoMockRecorder) DeadLetters(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DeadLetters", reflect.TypeOf((*MockNodeGRPCRepo)(nil).DeadLetters), ctx, addr)
}

// Dequeue mocks base method.
func (m *MockNodeGRPCRepo) Dequeue(ctx context.Context, addr string, spec entity.QueueSpec, max int) ([]entity.NodeMessage, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Dequeue", ctx, addr, spec, max)
	ret0, _ := ret[0].([]entity.NodeMessage)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Dequeue indicates an expected call of Dequeue.
func (mr *MockNodeGRPCRepoMockRecorder) Dequeue(ctx, addr, spec, max any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Dequeue", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Dequeue), ctx, addr, spec, max)
}

// DiscardMove mocks base method.
func (m *MockNodeGRPCRepo) DiscardMove(ctx context.Context, addr string, spec entity.QueueSpec, slots []uint16, moveID string) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "DiscardMove", ctx, addr, spec, slots, moveID)
	ret0, _ := ret[0].(error)
	return ret0
}

// DiscardMove indicates an expected call of DiscardMove.
func (mr *MockNodeGRPCRepoMockRecorder) DiscardMove(ctx, addr, spec, slots, moveID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "DiscardMove", reflect.TypeOf((*MockNodeGRPCRepo)(nil).DiscardMove), ctx, addr, spec, slots, moveID)
}

// Drop mocks base method.
func (m *MockNodeGRPCRepo) Drop(ctx context.Context, addr string, spec entity.QueueSpec) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drop", ctx, addr, spec)
	ret0, _ := ret[0].(error)
	return ret0
}

// Drop indicates an expected call of Drop.
func (mr *MockNodeGRPCRepoMockRecorder) Drop(ctx, addr, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Drop), ctx, addr, spec)
}

// Enqueue mocks base method.
func (m *MockNodeGRPCRepo) Enqueue(ctx context.Context, addr string, req entity.NodeEnqueue) (entity.NodeEnqueueResult, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Enqueue", ctx, addr, req)
	ret0, _ := ret[0].(entity.NodeEnqueueResult)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Enqueue indicates an expected call of Enqueue.
func (mr *MockNodeGRPCRepoMockRecorder) Enqueue(ctx, addr, req any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Enqueue", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Enqueue), ctx, addr, req)
}

// Freeze mocks base method.
func (m *MockNodeGRPCRepo) Freeze(ctx context.Context, addr string, spec entity.QueueSpec, slots []uint16) (entity.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Freeze", ctx, addr, spec, slots)
	ret0, _ := ret[0].(entity.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Freeze indicates an expected call of Freeze.
func (mr *MockNodeGRPCRepoMockRecorder) Freeze(ctx, addr, spec, slots any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Freeze", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Freeze), ctx, addr, spec, slots)
}

// Held mocks base method.
func (m *MockNodeGRPCRepo) Held(ctx context.Context, addr string) (entity.HeldResponse, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Held", ctx, addr)
	ret0, _ := ret[0].(entity.HeldResponse)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Held indicates an expected call of Held.
func (mr *MockNodeGRPCRepoMockRecorder) Held(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Held", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Held), ctx, addr)
}

// Nack mocks base method.
func (m *MockNodeGRPCRepo) Nack(ctx context.Context, addr string, spec entity.QueueSpec, receipt string, delay time.Duration) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Nack", ctx, addr, spec, receipt, delay)
	ret0, _ := ret[0].(error)
	return ret0
}

// Nack indicates an expected call of Nack.
func (mr *MockNodeGRPCRepoMockRecorder) Nack(ctx, addr, spec, receipt, delay any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Nack", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Nack), ctx, addr, spec, receipt, delay)
}

// PrepareMove mocks base method.
func (m *MockNodeGRPCRepo) PrepareMove(ctx context.Context, addr string, spec entity.QueueSpec, slots []uint16, moveID string) (entity.Transfer, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "PrepareMove", ctx, addr, spec, slots, moveID)
	ret0, _ := ret[0].(entity.Transfer)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// PrepareMove indicates an expected call of PrepareMove.
func (mr *MockNodeGRPCRepoMockRecorder) PrepareMove(ctx, addr, spec, slots, moveID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "PrepareMove", reflect.TypeOf((*MockNodeGRPCRepo)(nil).PrepareMove), ctx, addr, spec, slots, moveID)
}

// Stats mocks base method.
func (m *MockNodeGRPCRepo) Stats(ctx context.Context, addr string, spec entity.QueueSpec) (entity.NodeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Stats", ctx, addr, spec)
	ret0, _ := ret[0].(entity.NodeStats)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Stats indicates an expected call of Stats.
func (mr *MockNodeGRPCRepoMockRecorder) Stats(ctx, addr, spec any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Stats", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Stats), ctx, addr, spec)
}

// StatsAll mocks base method.
func (m *MockNodeGRPCRepo) StatsAll(ctx context.Context, addr string) (string, []entity.NodeStats, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "StatsAll", ctx, addr)
	ret0, _ := ret[0].(string)
	ret1, _ := ret[1].([]entity.NodeStats)
	ret2, _ := ret[2].(error)
	return ret0, ret1, ret2
}

// StatsAll indicates an expected call of StatsAll.
func (mr *MockNodeGRPCRepoMockRecorder) StatsAll(ctx, addr any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "StatsAll", reflect.TypeOf((*MockNodeGRPCRepo)(nil).StatsAll), ctx, addr)
}

// Subscribe mocks base method.
func (m *MockNodeGRPCRepo) Subscribe(ctx context.Context, addr, gatewayID string) (<-chan entity.WorkAvailable, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Subscribe", ctx, addr, gatewayID)
	ret0, _ := ret[0].(<-chan entity.WorkAvailable)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Subscribe indicates an expected call of Subscribe.
func (mr *MockNodeGRPCRepoMockRecorder) Subscribe(ctx, addr, gatewayID any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Subscribe", reflect.TypeOf((*MockNodeGRPCRepo)(nil).Subscribe), ctx, addr, gatewayID)
}
