// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.2
// - protoc             (unknown)
// source: queue/v1/queue.proto

package queuev1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	QueueService_Enqueue_FullMethodName     = "/ryuk.queue.v1.QueueService/Enqueue"
	QueueService_Dequeue_FullMethodName     = "/ryuk.queue.v1.QueueService/Dequeue"
	QueueService_Ack_FullMethodName         = "/ryuk.queue.v1.QueueService/Ack"
	QueueService_Nack_FullMethodName        = "/ryuk.queue.v1.QueueService/Nack"
	QueueService_Stats_FullMethodName       = "/ryuk.queue.v1.QueueService/Stats"
	QueueService_StatsAll_FullMethodName    = "/ryuk.queue.v1.QueueService/StatsAll"
	QueueService_Drop_FullMethodName        = "/ryuk.queue.v1.QueueService/Drop"
	QueueService_PrepareMove_FullMethodName = "/ryuk.queue.v1.QueueService/PrepareMove"
	QueueService_Absorb_FullMethodName      = "/ryuk.queue.v1.QueueService/Absorb"
	QueueService_DiscardMove_FullMethodName = "/ryuk.queue.v1.QueueService/DiscardMove"
	QueueService_AbortMove_FullMethodName   = "/ryuk.queue.v1.QueueService/AbortMove"
	QueueService_Freeze_FullMethodName      = "/ryuk.queue.v1.QueueService/Freeze"
	QueueService_Held_FullMethodName        = "/ryuk.queue.v1.QueueService/Held"
	QueueService_Subscribe_FullMethodName   = "/ryuk.queue.v1.QueueService/Subscribe"
	QueueService_Health_FullMethodName      = "/ryuk.queue.v1.QueueService/Health"
)

// QueueServiceClient is the client API for QueueService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type QueueServiceClient interface {
	Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error)
	Dequeue(ctx context.Context, in *DequeueRequest, opts ...grpc.CallOption) (*DequeueResponse, error)
	Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*Empty, error)
	Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*Empty, error)
	Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*QueueStats, error)
	StatsAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsAllResponse, error)
	Drop(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*Empty, error)
	// A handoff. PrepareMove snapshots without removing, so a move that fails
	// leaves this node still able to serve. DiscardMove is what finally removes,
	// and only runs once the new owner is serving; AbortMove puts them back.
	PrepareMove(ctx context.Context, in *SlotSet, opts ...grpc.CallOption) (*Transfer, error)
	Absorb(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*Empty, error)
	DiscardMove(ctx context.Context, in *SlotSet, opts ...grpc.CallOption) (*Empty, error)
	AbortMove(ctx context.Context, in *SlotSet, opts ...grpc.CallOption) (*Empty, error)
	// Freeze is the old destructive form, kept for whole-queue migration.
	Freeze(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*Transfer, error)
	// Held reports what this node has, so the gateway can reconcile it against
	// placement and repair anything a failed handoff left behind.
	Held(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeldResponse, error)
	// Subscribe is how a parked consumer is woken. Notification and dequeue are
	// separate so only one dequeue is ever issued: fanning a waiting dequeue out
	// to several nodes would lease messages nobody is processing.
	Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkAvailable], error)
	Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error)
}

type queueServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewQueueServiceClient(cc grpc.ClientConnInterface) QueueServiceClient {
	return &queueServiceClient{cc}
}

func (c *queueServiceClient) Enqueue(ctx context.Context, in *EnqueueRequest, opts ...grpc.CallOption) (*EnqueueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnqueueResponse)
	err := c.cc.Invoke(ctx, QueueService_Enqueue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Dequeue(ctx context.Context, in *DequeueRequest, opts ...grpc.CallOption) (*DequeueResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DequeueResponse)
	err := c.cc.Invoke(ctx, QueueService_Dequeue_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Ack(ctx context.Context, in *AckRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, QueueService_Ack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Nack(ctx context.Context, in *NackRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, QueueService_Nack_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Stats(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*QueueStats, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(QueueStats)
	err := c.cc.Invoke(ctx, QueueService_Stats_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) StatsAll(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*StatsAllResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(StatsAllResponse)
	err := c.cc.Invoke(ctx, QueueService_StatsAll_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Drop(ctx context.Context, in *StatsRequest, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, QueueService_Drop_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) PrepareMove(ctx context.Context, in *SlotSet, opts ...grpc.CallOption) (*Transfer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transfer)
	err := c.cc.Invoke(ctx, QueueService_PrepareMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Absorb(ctx context.Context, in *Transfer, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, QueueService_Absorb_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) DiscardMove(ctx context.Context, in *SlotSet, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, QueueService_DiscardMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) AbortMove(ctx context.Context, in *SlotSet, opts ...grpc.CallOption) (*Empty, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Empty)
	err := c.cc.Invoke(ctx, QueueService_AbortMove_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Freeze(ctx context.Context, in *FreezeRequest, opts ...grpc.CallOption) (*Transfer, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(Transfer)
	err := c.cc.Invoke(ctx, QueueService_Freeze_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Held(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HeldResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeldResponse)
	err := c.cc.Invoke(ctx, QueueService_Held_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *queueServiceClient) Subscribe(ctx context.Context, in *SubscribeRequest, opts ...grpc.CallOption) (grpc.ServerStreamingClient[WorkAvailable], error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	stream, err := c.cc.NewStream(ctx, &QueueService_ServiceDesc.Streams[0], QueueService_Subscribe_FullMethodName, cOpts...)
	if err != nil {
		return nil, err
	}
	x := &grpc.GenericClientStream[SubscribeRequest, WorkAvailable]{ClientStream: stream}
	if err := x.ClientStream.SendMsg(in); err != nil {
		return nil, err
	}
	if err := x.ClientStream.CloseSend(); err != nil {
		return nil, err
	}
	return x, nil
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueueService_SubscribeClient = grpc.ServerStreamingClient[WorkAvailable]

func (c *queueServiceClient) Health(ctx context.Context, in *Empty, opts ...grpc.CallOption) (*HealthResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HealthResponse)
	err := c.cc.Invoke(ctx, QueueService_Health_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// QueueServiceServer is the server API for QueueService service.
// All implementations must embed UnimplementedQueueServiceServer
// for forward compatibility.
type QueueServiceServer interface {
	Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error)
	Dequeue(context.Context, *DequeueRequest) (*DequeueResponse, error)
	Ack(context.Context, *AckRequest) (*Empty, error)
	Nack(context.Context, *NackRequest) (*Empty, error)
	Stats(context.Context, *StatsRequest) (*QueueStats, error)
	StatsAll(context.Context, *Empty) (*StatsAllResponse, error)
	Drop(context.Context, *StatsRequest) (*Empty, error)
	// A handoff. PrepareMove snapshots without removing, so a move that fails
	// leaves this node still able to serve. DiscardMove is what finally removes,
	// and only runs once the new owner is serving; AbortMove puts them back.
	PrepareMove(context.Context, *SlotSet) (*Transfer, error)
	Absorb(context.Context, *Transfer) (*Empty, error)
	DiscardMove(context.Context, *SlotSet) (*Empty, error)
	AbortMove(context.Context, *SlotSet) (*Empty, error)
	// Freeze is the old destructive form, kept for whole-queue migration.
	Freeze(context.Context, *FreezeRequest) (*Transfer, error)
	// Held reports what this node has, so the gateway can reconcile it against
	// placement and repair anything a failed handoff left behind.
	Held(context.Context, *Empty) (*HeldResponse, error)
	// Subscribe is how a parked consumer is woken. Notification and dequeue are
	// separate so only one dequeue is ever issued: fanning a waiting dequeue out
	// to several nodes would lease messages nobody is processing.
	Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[WorkAvailable]) error
	Health(context.Context, *Empty) (*HealthResponse, error)
	mustEmbedUnimplementedQueueServiceServer()
}

// UnimplementedQueueServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedQueueServiceServer struct{}

func (UnimplementedQueueServiceServer) Enqueue(context.Context, *EnqueueRequest) (*EnqueueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Enqueue not implemented")
}
func (UnimplementedQueueServiceServer) Dequeue(context.Context, *DequeueRequest) (*DequeueResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Dequeue not implemented")
}
func (UnimplementedQueueServiceServer) Ack(context.Context, *AckRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Ack not implemented")
}
func (UnimplementedQueueServiceServer) Nack(context.Context, *NackRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Nack not implemented")
}
func (UnimplementedQueueServiceServer) Stats(context.Context, *StatsRequest) (*QueueStats, error) {
	return nil, status.Error(codes.Unimplemented, "method Stats not implemented")
}
func (UnimplementedQueueServiceServer) StatsAll(context.Context, *Empty) (*StatsAllResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method StatsAll not implemented")
}
func (UnimplementedQueueServiceServer) Drop(context.Context, *StatsRequest) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Drop not implemented")
}
func (UnimplementedQueueServiceServer) PrepareMove(context.Context, *SlotSet) (*Transfer, error) {
	return nil, status.Error(codes.Unimplemented, "method PrepareMove not implemented")
}
func (UnimplementedQueueServiceServer) Absorb(context.Context, *Transfer) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method Absorb not implemented")
}
func (UnimplementedQueueServiceServer) DiscardMove(context.Context, *SlotSet) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method DiscardMove not implemented")
}
func (UnimplementedQueueServiceServer) AbortMove(context.Context, *SlotSet) (*Empty, error) {
	return nil, status.Error(codes.Unimplemented, "method AbortMove not implemented")
}
func (UnimplementedQueueServiceServer) Freeze(context.Context, *FreezeRequest) (*Transfer, error) {
	return nil, status.Error(codes.Unimplemented, "method Freeze not implemented")
}
func (UnimplementedQueueServiceServer) Held(context.Context, *Empty) (*HeldResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Held not implemented")
}
func (UnimplementedQueueServiceServer) Subscribe(*SubscribeRequest, grpc.ServerStreamingServer[WorkAvailable]) error {
	return status.Error(codes.Unimplemented, "method Subscribe not implemented")
}
func (UnimplementedQueueServiceServer) Health(context.Context, *Empty) (*HealthResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Health not implemented")
}
func (UnimplementedQueueServiceServer) mustEmbedUnimplementedQueueServiceServer() {}
func (UnimplementedQueueServiceServer) testEmbeddedByValue()                      {}

// UnsafeQueueServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to QueueServiceServer will
// result in compilation errors.
type UnsafeQueueServiceServer interface {
	mustEmbedUnimplementedQueueServiceServer()
}

func RegisterQueueServiceServer(s grpc.ServiceRegistrar, srv QueueServiceServer) {
	// If the following call panics, it indicates UnimplementedQueueServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&QueueService_ServiceDesc, srv)
}

func _QueueService_Enqueue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnqueueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Enqueue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Enqueue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Enqueue(ctx, req.(*EnqueueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Dequeue_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DequeueRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Dequeue(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Dequeue_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Dequeue(ctx, req.(*DequeueRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Ack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(AckRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Ack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Ack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Ack(ctx, req.(*AckRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Nack_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(NackRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Nack(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Nack_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Nack(ctx, req.(*NackRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Stats_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Stats(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Stats_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Stats(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_StatsAll_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).StatsAll(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_StatsAll_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).StatsAll(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Drop_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(StatsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Drop(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Drop_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Drop(ctx, req.(*StatsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_PrepareMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).PrepareMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_PrepareMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).PrepareMove(ctx, req.(*SlotSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Absorb_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Transfer)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Absorb(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Absorb_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Absorb(ctx, req.(*Transfer))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_DiscardMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).DiscardMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_DiscardMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).DiscardMove(ctx, req.(*SlotSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_AbortMove_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(SlotSet)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).AbortMove(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_AbortMove_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).AbortMove(ctx, req.(*SlotSet))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Freeze_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(FreezeRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Freeze(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Freeze_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Freeze(ctx, req.(*FreezeRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Held_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Held(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Held_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Held(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

func _QueueService_Subscribe_Handler(srv interface{}, stream grpc.ServerStream) error {
	m := new(SubscribeRequest)
	if err := stream.RecvMsg(m); err != nil {
		return err
	}
	return srv.(QueueServiceServer).Subscribe(m, &grpc.GenericServerStream[SubscribeRequest, WorkAvailable]{ServerStream: stream})
}

// This type alias is provided for backwards compatibility with existing code that references the prior non-generic stream type by name.
type QueueService_SubscribeServer = grpc.ServerStreamingServer[WorkAvailable]

func _QueueService_Health_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(Empty)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(QueueServiceServer).Health(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: QueueService_Health_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(QueueServiceServer).Health(ctx, req.(*Empty))
	}
	return interceptor(ctx, in, info, handler)
}

// QueueService_ServiceDesc is the grpc.ServiceDesc for QueueService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var QueueService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "ryuk.queue.v1.QueueService",
	HandlerType: (*QueueServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Enqueue",
			Handler:    _QueueService_Enqueue_Handler,
		},
		{
			MethodName: "Dequeue",
			Handler:    _QueueService_Dequeue_Handler,
		},
		{
			MethodName: "Ack",
			Handler:    _QueueService_Ack_Handler,
		},
		{
			MethodName: "Nack",
			Handler:    _QueueService_Nack_Handler,
		},
		{
			MethodName: "Stats",
			Handler:    _QueueService_Stats_Handler,
		},
		{
			MethodName: "StatsAll",
			Handler:    _QueueService_StatsAll_Handler,
		},
		{
			MethodName: "Drop",
			Handler:    _QueueService_Drop_Handler,
		},
		{
			MethodName: "PrepareMove",
			Handler:    _QueueService_PrepareMove_Handler,
		},
		{
			MethodName: "Absorb",
			Handler:    _QueueService_Absorb_Handler,
		},
		{
			MethodName: "DiscardMove",
			Handler:    _QueueService_DiscardMove_Handler,
		},
		{
			MethodName: "AbortMove",
			Handler:    _QueueService_AbortMove_Handler,
		},
		{
			MethodName: "Freeze",
			Handler:    _QueueService_Freeze_Handler,
		},
		{
			MethodName: "Held",
			Handler:    _QueueService_Held_Handler,
		},
		{
			MethodName: "Health",
			Handler:    _QueueService_Health_Handler,
		},
	},
	Streams: []grpc.StreamDesc{
		{
			StreamName:    "Subscribe",
			Handler:       _QueueService_Subscribe_Handler,
			ServerStreams: true,
		},
	},
	Metadata: "queue/v1/queue.proto",
}
