// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.12
// 	protoc        (unknown)
// source: queue/v1/queue.proto

package queuev1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// QueueSpec travels with every request so a node can materialise a queue it has
// not seen without a separate create call.
type QueueSpec struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	Org                   string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name                  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	VisibilityTimeoutNs   int64                  `protobuf:"varint,3,opt,name=visibility_timeout_ns,json=visibilityTimeoutNs,proto3" json:"visibility_timeout_ns,omitempty"`
	MaxRetries            uint32                 `protobuf:"varint,4,opt,name=max_retries,json=maxRetries,proto3" json:"max_retries,omitempty"`
	DefaultTtlNs          int64                  `protobuf:"varint,5,opt,name=default_ttl_ns,json=defaultTtlNs,proto3" json:"default_ttl_ns,omitempty"`
	StarvationThresholdNs int64                  `protobuf:"varint,6,opt,name=starvation_threshold_ns,json=starvationThresholdNs,proto3" json:"starvation_threshold_ns,omitempty"`
	StarvationReserve     float64                `protobuf:"fixed64,7,opt,name=starvation_reserve,json=starvationReserve,proto3" json:"starvation_reserve,omitempty"`
	MaxDepth              int64                  `protobuf:"varint,8,opt,name=max_depth,json=maxDepth,proto3" json:"max_depth,omitempty"`
	Distributed           bool                   `protobuf:"varint,9,opt,name=distributed,proto3" json:"distributed,omitempty"`
	Generation            uint64                 `protobuf:"varint,10,opt,name=generation,proto3" json:"generation,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *QueueSpec) Reset() {
	*x = QueueSpec{}
	mi := &file_queue_v1_queue_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueSpec) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueSpec) ProtoMessage() {}

func (x *QueueSpec) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueSpec.ProtoReflect.Descriptor instead.
func (*QueueSpec) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{0}
}

func (x *QueueSpec) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *QueueSpec) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueSpec) GetVisibilityTimeoutNs() int64 {
	if x != nil {
		return x.VisibilityTimeoutNs
	}
	return 0
}

func (x *QueueSpec) GetMaxRetries() uint32 {
	if x != nil {
		return x.MaxRetries
	}
	return 0
}

func (x *QueueSpec) GetDefaultTtlNs() int64 {
	if x != nil {
		return x.DefaultTtlNs
	}
	return 0
}

func (x *QueueSpec) GetStarvationThresholdNs() int64 {
	if x != nil {
		return x.StarvationThresholdNs
	}
	return 0
}

func (x *QueueSpec) GetStarvationReserve() float64 {
	if x != nil {
		return x.StarvationReserve
	}
	return 0
}

func (x *QueueSpec) GetMaxDepth() int64 {
	if x != nil {
		return x.MaxDepth
	}
	return 0
}

func (x *QueueSpec) GetDistributed() bool {
	if x != nil {
		return x.Distributed
	}
	return false
}

func (x *QueueSpec) GetGeneration() uint64 {
	if x != nil {
		return x.Generation
	}
	return 0
}

type EnqueueRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Spec  *QueueSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// Set when the caller has already chosen the slot, which it has to for a
	// grouped message so ordering holds.
	Slot           *uint32 `protobuf:"varint,2,opt,name=slot,proto3,oneof" json:"slot,omitempty"`
	Payload        []byte  `protobuf:"bytes,3,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority       uint32  `protobuf:"varint,4,opt,name=priority,proto3" json:"priority,omitempty"`
	GroupId        string  `protobuf:"bytes,5,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	TtlNs          int64   `protobuf:"varint,6,opt,name=ttl_ns,json=ttlNs,proto3" json:"ttl_ns,omitempty"`
	DeliverAfterNs int64   `protobuf:"varint,7,opt,name=deliver_after_ns,json=deliverAfterNs,proto3" json:"deliver_after_ns,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *EnqueueRequest) Reset() {
	*x = EnqueueRequest{}
	mi := &file_queue_v1_queue_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueRequest) ProtoMessage() {}

func (x *EnqueueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueRequest.ProtoReflect.Descriptor instead.
func (*EnqueueRequest) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{1}
}

func (x *EnqueueRequest) GetSpec() *QueueSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *EnqueueRequest) GetSlot() uint32 {
	if x != nil && x.Slot != nil {
		return *x.Slot
	}
	return 0
}

func (x *EnqueueRequest) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *EnqueueRequest) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *EnqueueRequest) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *EnqueueRequest) GetTtlNs() int64 {
	if x != nil {
		return x.TtlNs
	}
	return 0
}

func (x *EnqueueRequest) GetDeliverAfterNs() int64 {
	if x != nil {
		return x.DeliverAfterNs
	}
	return 0
}

type EnqueueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MessageId     string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Slot          uint32                 `protobuf:"varint,2,opt,name=slot,proto3" json:"slot,omitempty"`
	Seq           uint64                 `protobuf:"varint,3,opt,name=seq,proto3" json:"seq,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnqueueResponse) Reset() {
	*x = EnqueueResponse{}
	mi := &file_queue_v1_queue_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnqueueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnqueueResponse) ProtoMessage() {}

func (x *EnqueueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnqueueResponse.ProtoReflect.Descriptor instead.
func (*EnqueueResponse) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{2}
}

func (x *EnqueueResponse) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *EnqueueResponse) GetSlot() uint32 {
	if x != nil {
		return x.Slot
	}
	return 0
}

func (x *EnqueueResponse) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

type DequeueRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *QueueSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	MaxMessages   int32                  `protobuf:"varint,2,opt,name=max_messages,json=maxMessages,proto3" json:"max_messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueRequest) Reset() {
	*x = DequeueRequest{}
	mi := &file_queue_v1_queue_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueRequest) ProtoMessage() {}

func (x *DequeueRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueRequest.ProtoReflect.Descriptor instead.
func (*DequeueRequest) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{3}
}

func (x *DequeueRequest) GetSpec() *QueueSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *DequeueRequest) GetMaxMessages() int32 {
	if x != nil {
		return x.MaxMessages
	}
	return 0
}

type DeliveredMessage struct {
	state            protoimpl.MessageState `protogen:"open.v1"`
	MessageId        string                 `protobuf:"bytes,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	Payload          []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority         uint32                 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	GroupId          string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Attempts         uint32                 `protobuf:"varint,5,opt,name=attempts,proto3" json:"attempts,omitempty"`
	EnqueuedAtUnixNs int64                  `protobuf:"varint,6,opt,name=enqueued_at_unix_ns,json=enqueuedAtUnixNs,proto3" json:"enqueued_at_unix_ns,omitempty"`
	Receipt          string                 `protobuf:"bytes,7,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields    protoimpl.UnknownFields
	sizeCache        protoimpl.SizeCache
}

func (x *DeliveredMessage) Reset() {
	*x = DeliveredMessage{}
	mi := &file_queue_v1_queue_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeliveredMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeliveredMessage) ProtoMessage() {}

func (x *DeliveredMessage) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeliveredMessage.ProtoReflect.Descriptor instead.
func (*DeliveredMessage) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{4}
}

func (x *DeliveredMessage) GetMessageId() string {
	if x != nil {
		return x.MessageId
	}
	return ""
}

func (x *DeliveredMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *DeliveredMessage) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *DeliveredMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *DeliveredMessage) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

func (x *DeliveredMessage) GetEnqueuedAtUnixNs() int64 {
	if x != nil {
		return x.EnqueuedAtUnixNs
	}
	return 0
}

func (x *DeliveredMessage) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

type DequeueResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*DeliveredMessage    `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DequeueResponse) Reset() {
	*x = DequeueResponse{}
	mi := &file_queue_v1_queue_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DequeueResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DequeueResponse) ProtoMessage() {}

func (x *DequeueResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DequeueResponse.ProtoReflect.Descriptor instead.
func (*DequeueResponse) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{5}
}

func (x *DequeueResponse) GetMessages() []*DeliveredMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

type AckRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *QueueSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Receipt       string                 `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AckRequest) Reset() {
	*x = AckRequest{}
	mi := &file_queue_v1_queue_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AckRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AckRequest) ProtoMessage() {}

func (x *AckRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AckRequest.ProtoReflect.Descriptor instead.
func (*AckRequest) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{6}
}

func (x *AckRequest) GetSpec() *QueueSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *AckRequest) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

type NackRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *QueueSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	Receipt       string                 `protobuf:"bytes,2,opt,name=receipt,proto3" json:"receipt,omitempty"`
	DelayNs       int64                  `protobuf:"varint,3,opt,name=delay_ns,json=delayNs,proto3" json:"delay_ns,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *NackRequest) Reset() {
	*x = NackRequest{}
	mi := &file_queue_v1_queue_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *NackRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*NackRequest) ProtoMessage() {}

func (x *NackRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use NackRequest.ProtoReflect.Descriptor instead.
func (*NackRequest) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{7}
}

func (x *NackRequest) GetSpec() *QueueSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *NackRequest) GetReceipt() string {
	if x != nil {
		return x.Receipt
	}
	return ""
}

func (x *NackRequest) GetDelayNs() int64 {
	if x != nil {
		return x.DelayNs
	}
	return 0
}

type Empty struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Empty) Reset() {
	*x = Empty{}
	mi := &file_queue_v1_queue_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Empty) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Empty) ProtoMessage() {}

func (x *Empty) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Empty.ProtoReflect.Descriptor instead.
func (*Empty) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{8}
}

type StatsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Spec          *QueueSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsRequest) Reset() {
	*x = StatsRequest{}
	mi := &file_queue_v1_queue_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsRequest) ProtoMessage() {}

func (x *StatsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsRequest.ProtoReflect.Descriptor instead.
func (*StatsRequest) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{9}
}

func (x *StatsRequest) GetSpec() *QueueSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

type FreezeRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Spec  *QueueSpec             `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	// Empty means every slot this node holds for the queue. A distributed queue
	// moves one slot at a time, so only those are named.
	Slots         []uint32 `protobuf:"varint,2,rep,packed,name=slots,proto3" json:"slots,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *FreezeRequest) Reset() {
	*x = FreezeRequest{}
	mi := &file_queue_v1_queue_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *FreezeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*FreezeRequest) ProtoMessage() {}

func (x *FreezeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use FreezeRequest.ProtoReflect.Descriptor instead.
func (*FreezeRequest) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{10}
}

func (x *FreezeRequest) GetSpec() *QueueSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *FreezeRequest) GetSlots() []uint32 {
	if x != nil {
		return x.Slots
	}
	return nil
}

type QueueStats struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	Org   string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name  string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	// ready is bucketed low, medium, high -- the granularity metrics report at.
	Ready         []int64 `protobuf:"varint,3,rep,packed,name=ready,proto3" json:"ready,omitempty"`
	InFlight      int64   `protobuf:"varint,4,opt,name=in_flight,json=inFlight,proto3" json:"in_flight,omitempty"`
	Delayed       int64   `protobuf:"varint,5,opt,name=delayed,proto3" json:"delayed,omitempty"`
	OldestAgeNs   int64   `protobuf:"varint,6,opt,name=oldest_age_ns,json=oldestAgeNs,proto3" json:"oldest_age_ns,omitempty"`
	Enqueued      uint64  `protobuf:"varint,7,opt,name=enqueued,proto3" json:"enqueued,omitempty"`
	Acked         uint64  `protobuf:"varint,8,opt,name=acked,proto3" json:"acked,omitempty"`
	Expired       uint64  `protobuf:"varint,9,opt,name=expired,proto3" json:"expired,omitempty"`
	Requeued      uint64  `protobuf:"varint,10,opt,name=requeued,proto3" json:"requeued,omitempty"`
	DeadLettered  uint64  `protobuf:"varint,11,opt,name=dead_lettered,json=deadLettered,proto3" json:"dead_lettered,omitempty"`
	Escapes       uint64  `protobuf:"varint,12,opt,name=escapes,proto3" json:"escapes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *QueueStats) Reset() {
	*x = QueueStats{}
	mi := &file_queue_v1_queue_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *QueueStats) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*QueueStats) ProtoMessage() {}

func (x *QueueStats) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use QueueStats.ProtoReflect.Descriptor instead.
func (*QueueStats) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{11}
}

func (x *QueueStats) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *QueueStats) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *QueueStats) GetReady() []int64 {
	if x != nil {
		return x.Ready
	}
	return nil
}

func (x *QueueStats) GetInFlight() int64 {
	if x != nil {
		return x.InFlight
	}
	return 0
}

func (x *QueueStats) GetDelayed() int64 {
	if x != nil {
		return x.Delayed
	}
	return 0
}

func (x *QueueStats) GetOldestAgeNs() int64 {
	if x != nil {
		return x.OldestAgeNs
	}
	return 0
}

func (x *QueueStats) GetEnqueued() uint64 {
	if x != nil {
		return x.Enqueued
	}
	return 0
}

func (x *QueueStats) GetAcked() uint64 {
	if x != nil {
		return x.Acked
	}
	return 0
}

func (x *QueueStats) GetExpired() uint64 {
	if x != nil {
		return x.Expired
	}
	return 0
}

func (x *QueueStats) GetRequeued() uint64 {
	if x != nil {
		return x.Requeued
	}
	return 0
}

func (x *QueueStats) GetDeadLettered() uint64 {
	if x != nil {
		return x.DeadLettered
	}
	return 0
}

func (x *QueueStats) GetEscapes() uint64 {
	if x != nil {
		return x.Escapes
	}
	return 0
}

type StatsAllResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	NodeId        string                 `protobuf:"bytes,1,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	Queues        []*QueueStats          `protobuf:"bytes,2,rep,name=queues,proto3" json:"queues,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *StatsAllResponse) Reset() {
	*x = StatsAllResponse{}
	mi := &file_queue_v1_queue_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *StatsAllResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*StatsAllResponse) ProtoMessage() {}

func (x *StatsAllResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use StatsAllResponse.ProtoReflect.Descriptor instead.
func (*StatsAllResponse) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{12}
}

func (x *StatsAllResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

func (x *StatsAllResponse) GetQueues() []*QueueStats {
	if x != nil {
		return x.Queues
	}
	return nil
}

type WireMessage struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	Id                 string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Payload            []byte                 `protobuf:"bytes,2,opt,name=payload,proto3" json:"payload,omitempty"`
	Priority           uint32                 `protobuf:"varint,3,opt,name=priority,proto3" json:"priority,omitempty"`
	GroupId            string                 `protobuf:"bytes,4,opt,name=group_id,json=groupId,proto3" json:"group_id,omitempty"`
	Seq                uint64                 `protobuf:"varint,5,opt,name=seq,proto3" json:"seq,omitempty"`
	EnqueuedAtUnixNs   int64                  `protobuf:"varint,6,opt,name=enqueued_at_unix_ns,json=enqueuedAtUnixNs,proto3" json:"enqueued_at_unix_ns,omitempty"`
	ExpiresAtUnixNs    int64                  `protobuf:"varint,7,opt,name=expires_at_unix_ns,json=expiresAtUnixNs,proto3" json:"expires_at_unix_ns,omitempty"`
	DeliverAfterUnixNs int64                  `protobuf:"varint,8,opt,name=deliver_after_unix_ns,json=deliverAfterUnixNs,proto3" json:"deliver_after_unix_ns,omitempty"`
	Attempts           uint32                 `protobuf:"varint,9,opt,name=attempts,proto3" json:"attempts,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *WireMessage) Reset() {
	*x = WireMessage{}
	mi := &file_queue_v1_queue_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WireMessage) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WireMessage) ProtoMessage() {}

func (x *WireMessage) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WireMessage.ProtoReflect.Descriptor instead.
func (*WireMessage) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{13}
}

func (x *WireMessage) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *WireMessage) GetPayload() []byte {
	if x != nil {
		return x.Payload
	}
	return nil
}

func (x *WireMessage) GetPriority() uint32 {
	if x != nil {
		return x.Priority
	}
	return 0
}

func (x *WireMessage) GetGroupId() string {
	if x != nil {
		return x.GroupId
	}
	return ""
}

func (x *WireMessage) GetSeq() uint64 {
	if x != nil {
		return x.Seq
	}
	return 0
}

func (x *WireMessage) GetEnqueuedAtUnixNs() int64 {
	if x != nil {
		return x.EnqueuedAtUnixNs
	}
	return 0
}

func (x *WireMessage) GetExpiresAtUnixNs() int64 {
	if x != nil {
		return x.ExpiresAtUnixNs
	}
	return 0
}

func (x *WireMessage) GetDeliverAfterUnixNs() int64 {
	if x != nil {
		return x.DeliverAfterUnixNs
	}
	return 0
}

func (x *WireMessage) GetAttempts() uint32 {
	if x != nil {
		return x.Attempts
	}
	return 0
}

type SlotMessages struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Messages      []*WireMessage         `protobuf:"bytes,1,rep,name=messages,proto3" json:"messages,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SlotMessages) Reset() {
	*x = SlotMessages{}
	mi := &file_queue_v1_queue_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SlotMessages) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SlotMessages) ProtoMessage() {}

func (x *SlotMessages) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SlotMessages.ProtoReflect.Descriptor instead.
func (*SlotMessages) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{14}
}

func (x *SlotMessages) GetMessages() []*WireMessage {
	if x != nil {
		return x.Messages
	}
	return nil
}

// Transfer carries a queue's contents to its new owner, keyed by slot so
// placement survives the move.
type Transfer struct {
	state         protoimpl.MessageState   `protogen:"open.v1"`
	Spec          *QueueSpec               `protobuf:"bytes,1,opt,name=spec,proto3" json:"spec,omitempty"`
	BySlot        map[uint32]*SlotMessages `protobuf:"bytes,2,rep,name=by_slot,json=bySlot,proto3" json:"by_slot,omitempty" protobuf_key:"varint,1,opt,name=key" protobuf_val:"bytes,2,opt,name=value"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Transfer) Reset() {
	*x = Transfer{}
	mi := &file_queue_v1_queue_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Transfer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Transfer) ProtoMessage() {}

func (x *Transfer) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Transfer.ProtoReflect.Descriptor instead.
func (*Transfer) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{15}
}

func (x *Transfer) GetSpec() *QueueSpec {
	if x != nil {
		return x.Spec
	}
	return nil
}

func (x *Transfer) GetBySlot() map[uint32]*SlotMessages {
	if x != nil {
		return x.BySlot
	}
	return nil
}

type SubscribeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	GatewayId     string                 `protobuf:"bytes,1,opt,name=gateway_id,json=gatewayId,proto3" json:"gateway_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeRequest) Reset() {
	*x = SubscribeRequest{}
	mi := &file_queue_v1_queue_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeRequest) ProtoMessage() {}

func (x *SubscribeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeRequest.ProtoReflect.Descriptor instead.
func (*SubscribeRequest) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{16}
}

func (x *SubscribeRequest) GetGatewayId() string {
	if x != nil {
		return x.GatewayId
	}
	return ""
}

// WorkAvailable is pushed when a queue on this node gains work. A gateway keeps
// one stream per node, not one per queue and not one per waiting consumer.
type WorkAvailable struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Org           string                 `protobuf:"bytes,1,opt,name=org,proto3" json:"org,omitempty"`
	Name          string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	BestPriority  uint32                 `protobuf:"varint,3,opt,name=best_priority,json=bestPriority,proto3" json:"best_priority,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *WorkAvailable) Reset() {
	*x = WorkAvailable{}
	mi := &file_queue_v1_queue_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *WorkAvailable) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*WorkAvailable) ProtoMessage() {}

func (x *WorkAvailable) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use WorkAvailable.ProtoReflect.Descriptor instead.
func (*WorkAvailable) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{17}
}

func (x *WorkAvailable) GetOrg() string {
	if x != nil {
		return x.Org
	}
	return ""
}

func (x *WorkAvailable) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *WorkAvailable) GetBestPriority() uint32 {
	if x != nil {
		return x.BestPriority
	}
	return 0
}

type HealthResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        string                 `protobuf:"bytes,1,opt,name=status,proto3" json:"status,omitempty"`
	NodeId        string                 `protobuf:"bytes,2,opt,name=node_id,json=nodeId,proto3" json:"node_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HealthResponse) Reset() {
	*x = HealthResponse{}
	mi := &file_queue_v1_queue_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HealthResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HealthResponse) ProtoMessage() {}

func (x *HealthResponse) ProtoReflect() protoreflect.Message {
	mi := &file_queue_v1_queue_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HealthResponse.ProtoReflect.Descriptor instead.
func (*HealthResponse) Descriptor() ([]byte, []int) {
	return file_queue_v1_queue_proto_rawDescGZIP(), []int{18}
}

func (x *HealthResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

func (x *HealthResponse) GetNodeId() string {
	if x != nil {
		return x.NodeId
	}
	return ""
}

var File_queue_v1_queue_proto protoreflect.FileDescriptor

const file_queue_v1_queue_proto_rawDesc = "" +
	"\n" +
	"\x14queue/v1/queue.proto\x12\rryuk.queue.v1\"\xf2\x02\n" +
	"\tQueueSpec\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x122\n" +
	"\x15visibility_timeout_ns\x18\x03 \x01(\x03R\x13visibilityTimeoutNs\x12\x1f\n" +
	"\vmax_retries\x18\x04 \x01(\rR\n" +
	"maxRetries\x12$\n" +
	"\x0edefault_ttl_ns\x18\x05 \x01(\x03R\fdefaultTtlNs\x126\n" +
	"\x17starvation_threshold_ns\x18\x06 \x01(\x03R\x15starvationThresholdNs\x12-\n" +
	"\x12starvation_reserve\x18\a \x01(\x01R\x11starvationReserve\x12\x1b\n" +
	"\tmax_depth\x18\b \x01(\x03R\bmaxDepth\x12 \n" +
	"\vdistributed\x18\t \x01(\bR\vdistributed\x12\x1e\n" +
	"\n" +
	"generation\x18\n" +
	" \x01(\x04R\n" +
	"generation\"\xf2\x01\n" +
	"\x0eEnqueueRequest\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.ryuk.queue.v1.QueueSpecR\x04spec\x12\x17\n" +
	"\x04slot\x18\x02 \x01(\rH\x00R\x04slot\x88\x01\x01\x12\x18\n" +
	"\apayload\x18\x03 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x04 \x01(\rR\bpriority\x12\x19\n" +
	"\bgroup_id\x18\x05 \x01(\tR\agroupId\x12\x15\n" +
	"\x06ttl_ns\x18\x06 \x01(\x03R\x05ttlNs\x12(\n" +
	"\x10deliver_after_ns\x18\a \x01(\x03R\x0edeliverAfterNsB\a\n" +
	"\x05_slot\"V\n" +
	"\x0fEnqueueResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x12\n" +
	"\x04slot\x18\x02 \x01(\rR\x04slot\x12\x10\n" +
	"\x03seq\x18\x03 \x01(\x04R\x03seq\"a\n" +
	"\x0eDequeueRequest\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.ryuk.queue.v1.QueueSpecR\x04spec\x12!\n" +
	"\fmax_messages\x18\x02 \x01(\x05R\vmaxMessages\"\xe7\x01\n" +
	"\x10DeliveredMessage\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\tR\tmessageId\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12\x1a\n" +
	"\battempts\x18\x05 \x01(\rR\battempts\x12-\n" +
	"\x13enqueued_at_unix_ns\x18\x06 \x01(\x03R\x10enqueuedAtUnixNs\x12\x18\n" +
	"\areceipt\x18\a \x01(\tR\areceipt\"N\n" +
	"\x0fDequeueResponse\x12;\n" +
	"\bmessages\x18\x01 \x03(\v2\x1f.ryuk.queue.v1.DeliveredMessageR\bmessages\"T\n" +
	"\n" +
	"AckRequest\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.ryuk.queue.v1.QueueSpecR\x04spec\x12\x18\n" +
	"\areceipt\x18\x02 \x01(\tR\areceipt\"p\n" +
	"\vNackRequest\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.ryuk.queue.v1.QueueSpecR\x04spec\x12\x18\n" +
	"\areceipt\x18\x02 \x01(\tR\areceipt\x12\x19\n" +
	"\bdelay_ns\x18\x03 \x01(\x03R\adelayNs\"\a\n" +
	"\x05Empty\"<\n" +
	"\fStatsRequest\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.ryuk.queue.v1.QueueSpecR\x04spec\"S\n" +
	"\rFreezeRequest\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.ryuk.queue.v1.QueueSpecR\x04spec\x12\x14\n" +
	"\x05slots\x18\x02 \x03(\rR\x05slots\"\xca\x02\n" +
	"\n" +
	"QueueStats\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12\x14\n" +
	"\x05ready\x18\x03 \x03(\x03R\x05ready\x12\x1b\n" +
	"\tin_flight\x18\x04 \x01(\x03R\binFlight\x12\x18\n" +
	"\adelayed\x18\x05 \x01(\x03R\adelayed\x12\"\n" +
	"\roldest_age_ns\x18\x06 \x01(\x03R\voldestAgeNs\x12\x1a\n" +
	"\benqueued\x18\a \x01(\x04R\benqueued\x12\x14\n" +
	"\x05acked\x18\b \x01(\x04R\x05acked\x12\x18\n" +
	"\aexpired\x18\t \x01(\x04R\aexpired\x12\x1a\n" +
	"\brequeued\x18\n" +
	" \x01(\x04R\brequeued\x12#\n" +
	"\rdead_lettered\x18\v \x01(\x04R\fdeadLettered\x12\x18\n" +
	"\aescapes\x18\f \x01(\x04R\aescapes\"^\n" +
	"\x10StatsAllResponse\x12\x17\n" +
	"\anode_id\x18\x01 \x01(\tR\x06nodeId\x121\n" +
	"\x06queues\x18\x02 \x03(\v2\x19.ryuk.queue.v1.QueueStatsR\x06queues\"\xab\x02\n" +
	"\vWireMessage\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\apayload\x18\x02 \x01(\fR\apayload\x12\x1a\n" +
	"\bpriority\x18\x03 \x01(\rR\bpriority\x12\x19\n" +
	"\bgroup_id\x18\x04 \x01(\tR\agroupId\x12\x10\n" +
	"\x03seq\x18\x05 \x01(\x04R\x03seq\x12-\n" +
	"\x13enqueued_at_unix_ns\x18\x06 \x01(\x03R\x10enqueuedAtUnixNs\x12+\n" +
	"\x12expires_at_unix_ns\x18\a \x01(\x03R\x0fexpiresAtUnixNs\x121\n" +
	"\x15deliver_after_unix_ns\x18\b \x01(\x03R\x12deliverAfterUnixNs\x12\x1a\n" +
	"\battempts\x18\t \x01(\rR\battempts\"F\n" +
	"\fSlotMessages\x126\n" +
	"\bmessages\x18\x01 \x03(\v2\x1a.ryuk.queue.v1.WireMessageR\bmessages\"\xce\x01\n" +
	"\bTransfer\x12,\n" +
	"\x04spec\x18\x01 \x01(\v2\x18.ryuk.queue.v1.QueueSpecR\x04spec\x12<\n" +
	"\aby_slot\x18\x02 \x03(\v2#.ryuk.queue.v1.Transfer.BySlotEntryR\x06bySlot\x1aV\n" +
	"\vBySlotEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\rR\x03key\x121\n" +
	"\x05value\x18\x02 \x01(\v2\x1b.ryuk.queue.v1.SlotMessagesR\x05value:\x028\x01\"1\n" +
	"\x10SubscribeRequest\x12\x1d\n" +
	"\n" +
	"gateway_id\x18\x01 \x01(\tR\tgatewayId\"Z\n" +
	"\rWorkAvailable\x12\x10\n" +
	"\x03org\x18\x01 \x01(\tR\x03org\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12#\n" +
	"\rbest_priority\x18\x03 \x01(\rR\fbestPriority\"A\n" +
	"\x0eHealthResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\tR\x06status\x12\x17\n" +
	"\anode_id\x18\x02 \x01(\tR\x06nodeId2\xda\x05\n" +
	"\fQueueService\x12H\n" +
	"\aEnqueue\x12\x1d.ryuk.queue.v1.EnqueueRequest\x1a\x1e.ryuk.queue.v1.EnqueueResponse\x12H\n" +
	"\aDequeue\x12\x1d.ryuk.queue.v1.DequeueRequest\x1a\x1e.ryuk.queue.v1.DequeueResponse\x126\n" +
	"\x03Ack\x12\x19.ryuk.queue.v1.AckRequest\x1a\x14.ryuk.queue.v1.Empty\x128\n" +
	"\x04Nack\x12\x1a.ryuk.queue.v1.NackRequest\x1a\x14.ryuk.queue.v1.Empty\x12?\n" +
	"\x05Stats\x12\x1b.ryuk.queue.v1.StatsRequest\x1a\x19.ryuk.queue.v1.QueueStats\x12A\n" +
	"\bStatsAll\x12\x14.ryuk.queue.v1.Empty\x1a\x1f.ryuk.queue.v1.StatsAllResponse\x129\n" +
	"\x04Drop\x12\x1b.ryuk.queue.v1.StatsRequest\x1a\x14.ryuk.queue.v1.Empty\x12?\n" +
	"\x06Freeze\x12\x1c.ryuk.queue.v1.FreezeRequest\x1a\x17.ryuk.queue.v1.Transfer\x127\n" +
	"\x06Absorb\x12\x17.ryuk.queue.v1.Transfer\x1a\x14.ryuk.queue.v1.Empty\x12L\n" +
	"\tSubscribe\x12\x1f.ryuk.queue.v1.SubscribeRequest\x1a\x1c.ryuk.queue.v1.WorkAvailable0\x01\x12=\n" +
	"\x06Health\x12\x14.ryuk.queue.v1.Empty\x1a\x1d.ryuk.queue.v1.HealthResponseB<Z:github.com/harryv2/ryuk-dpq/backend/proto/queue/v1;queuev1b\x06proto3"

var (
	file_queue_v1_queue_proto_rawDescOnce sync.Once
	file_queue_v1_queue_proto_rawDescData []byte
)

func file_queue_v1_queue_proto_rawDescGZIP() []byte {
	file_queue_v1_queue_proto_rawDescOnce.Do(func() {
		file_queue_v1_queue_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_queue_v1_queue_proto_rawDesc), len(file_queue_v1_queue_proto_rawDesc)))
	})
	return file_queue_v1_queue_proto_rawDescData
}

var file_queue_v1_queue_proto_msgTypes = make([]protoimpl.MessageInfo, 20)
var file_queue_v1_queue_proto_goTypes = []any{
	(*QueueSpec)(nil),        // 0: ryuk.queue.v1.QueueSpec
	(*EnqueueRequest)(nil),   // 1: ryuk.queue.v1.EnqueueRequest
	(*EnqueueResponse)(nil),  // 2: ryuk.queue.v1.EnqueueResponse
	(*DequeueRequest)(nil),   // 3: ryuk.queue.v1.DequeueRequest
	(*DeliveredMessage)(nil), // 4: ryuk.queue.v1.DeliveredMessage
	(*DequeueResponse)(nil),  // 5: ryuk.queue.v1.DequeueResponse
	(*AckRequest)(nil),       // 6: ryuk.queue.v1.AckRequest
	(*NackRequest)(nil),      // 7: ryuk.queue.v1.NackRequest
	(*Empty)(nil),            // 8: ryuk.queue.v1.Empty
	(*StatsRequest)(nil),     // 9: ryuk.queue.v1.StatsRequest
	(*FreezeRequest)(nil),    // 10: ryuk.queue.v1.FreezeRequest
	(*QueueStats)(nil),       // 11: ryuk.queue.v1.QueueStats
	(*StatsAllResponse)(nil), // 12: ryuk.queue.v1.StatsAllResponse
	(*WireMessage)(nil),      // 13: ryuk.queue.v1.WireMessage
	(*SlotMessages)(nil),     // 14: ryuk.queue.v1.SlotMessages
	(*Transfer)(nil),         // 15: ryuk.queue.v1.Transfer
	(*SubscribeRequest)(nil), // 16: ryuk.queue.v1.SubscribeRequest
	(*WorkAvailable)(nil),    // 17: ryuk.queue.v1.WorkAvailable
	(*HealthResponse)(nil),   // 18: ryuk.queue.v1.HealthResponse
	nil,                      // 19: ryuk.queue.v1.Transfer.BySlotEntry
}
var file_queue_v1_queue_proto_depIdxs = []int32{
	0,  // 0: ryuk.queue.v1.EnqueueRequest.spec:type_name -> ryuk.queue.v1.QueueSpec
	0,  // 1: ryuk.queue.v1.DequeueRequest.spec:type_name -> ryuk.queue.v1.QueueSpec
	4,  // 2: ryuk.queue.v1.DequeueResponse.messages:type_name -> ryuk.queue.v1.DeliveredMessage
	0,  // 3: ryuk.queue.v1.AckRequest.spec:type_name -> ryuk.queue.v1.QueueSpec
	0,  // 4: ryuk.queue.v1.NackRequest.spec:type_name -> ryuk.queue.v1.QueueSpec
	0,  // 5: ryuk.queue.v1.StatsRequest.spec:type_name -> ryuk.queue.v1.QueueSpec
	0,  // 6: ryuk.queue.v1.FreezeRequest.spec:type_name -> ryuk.queue.v1.QueueSpec
	11, // 7: ryuk.queue.v1.StatsAllResponse.queues:type_name -> ryuk.queue.v1.QueueStats
	13, // 8: ryuk.queue.v1.SlotMessages.messages:type_name -> ryuk.queue.v1.WireMessage
	0,  // 9: ryuk.queue.v1.Transfer.spec:type_name -> ryuk.queue.v1.QueueSpec
	19, // 10: ryuk.queue.v1.Transfer.by_slot:type_name -> ryuk.queue.v1.Transfer.BySlotEntry
	14, // 11: ryuk.queue.v1.Transfer.BySlotEntry.value:type_name -> ryuk.queue.v1.SlotMessages
	1,  // 12: ryuk.queue.v1.QueueService.Enqueue:input_type -> ryuk.queue.v1.EnqueueRequest
	3,  // 13: ryuk.queue.v1.QueueService.Dequeue:input_type -> ryuk.queue.v1.DequeueRequest
	6,  // 14: ryuk.queue.v1.QueueService.Ack:input_type -> ryuk.queue.v1.AckRequest
	7,  // 15: ryuk.queue.v1.QueueService.Nack:input_type -> ryuk.queue.v1.NackRequest
	9,  // 16: ryuk.queue.v1.QueueService.Stats:input_type -> ryuk.queue.v1.StatsRequest
	8,  // 17: ryuk.queue.v1.QueueService.StatsAll:input_type -> ryuk.queue.v1.Empty
	9,  // 18: ryuk.queue.v1.QueueService.Drop:input_type -> ryuk.queue.v1.StatsRequest
	10, // 19: ryuk.queue.v1.QueueService.Freeze:input_type -> ryuk.queue.v1.FreezeRequest
	15, // 20: ryuk.queue.v1.QueueService.Absorb:input_type -> ryuk.queue.v1.Transfer
	16, // 21: ryuk.queue.v1.QueueService.Subscribe:input_type -> ryuk.queue.v1.SubscribeRequest
	8,  // 22: ryuk.queue.v1.QueueService.Health:input_type -> ryuk.queue.v1.Empty
	2,  // 23: ryuk.queue.v1.QueueService.Enqueue:output_type -> ryuk.queue.v1.EnqueueResponse
	5,  // 24: ryuk.queue.v1.QueueService.Dequeue:output_type -> ryuk.queue.v1.DequeueResponse
	8,  // 25: ryuk.queue.v1.QueueService.Ack:output_type -> ryuk.queue.v1.Empty
	8,  // 26: ryuk.queue.v1.QueueService.Nack:output_type -> ryuk.queue.v1.Empty
	11, // 27: ryuk.queue.v1.QueueService.Stats:output_type -> ryuk.queue.v1.QueueStats
	12, // 28: ryuk.queue.v1.QueueService.StatsAll:output_type -> ryuk.queue.v1.StatsAllResponse
	8,  // 29: ryuk.queue.v1.QueueService.Drop:output_type -> ryuk.queue.v1.Empty
	15, // 30: ryuk.queue.v1.QueueService.Freeze:output_type -> ryuk.queue.v1.Transfer
	8,  // 31: ryuk.queue.v1.QueueService.Absorb:output_type -> ryuk.queue.v1.Empty
	17, // 32: ryuk.queue.v1.QueueService.Subscribe:output_type -> ryuk.queue.v1.WorkAvailable
	18, // 33: ryuk.queue.v1.QueueService.Health:output_type -> ryuk.queue.v1.HealthResponse
	23, // [23:34] is the sub-list for method output_type
	12, // [12:23] is the sub-list for method input_type
	12, // [12:12] is the sub-list for extension type_name
	12, // [12:12] is the sub-list for extension extendee
	0,  // [0:12] is the sub-list for field type_name
}

func init() { file_queue_v1_queue_proto_init() }
func file_queue_v1_queue_proto_init() {
	if File_queue_v1_queue_proto != nil {
		return
	}
	file_queue_v1_queue_proto_msgTypes[1].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_queue_v1_queue_proto_rawDesc), len(file_queue_v1_queue_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   20,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_queue_v1_queue_proto_goTypes,
		DependencyIndexes: file_queue_v1_queue_proto_depIdxs,
		MessageInfos:      file_queue_v1_queue_proto_msgTypes,
	}.Build()
	File_queue_v1_queue_proto = out.File
	file_queue_v1_queue_proto_goTypes = nil
	file_queue_v1_queue_proto_depIdxs = nil
}
