// Code generated by Wire. DO NOT EDIT.

//go:generate go run -mod=mod github.com/google/wire/cmd/wire
//go:build !wireinject
// +build !wireinject

package logic

import (
	"github.com/harryv2/ryuk-dpq/backend/config"
	"github.com/harryv2/ryuk-dpq/backend/queue/entity"
	"github.com/harryv2/ryuk-dpq/backend/queue/repo/membershipetcd"
)

// Injectors from container.go:

// InitialiseQueueLogic builds the node's god struct. Identity and the log
// factory come from the data directory, so a node needs no configuration beyond
// where its data lives and how to reach etcd.
func InitialiseQueueLogic(cfg config.Node) (*QueueLogic, error) {
	dataDir := ProvideDataDir(cfg)
	nodeIdentity, err := ProvideNodeIdentity(dataDir)
	if err != nil {
		return nil, err
	}
	incarnation, err := ProvideIncarnation(dataDir)
	if err != nil {
		return nil, err
	}
	logicConfig := ProvideConfig(cfg, nodeIdentity, incarnation)
	logger := ProvideLogger(cfg)
	clock := ProvideClock()
	entityWALFactory := ProvideWALFactory(cfg, dataDir, incarnation)
	queueLogic := New(logicConfig, logger, clock, entityWALFactory)
	return queueLogic, nil
}

// InitialiseMembership is separate because a node can run without etcd, which is
// what makes a single-process test possible.
func InitialiseMembership(cfg config.Node) (*membershipetcd.Repo, func(), error) {
	endpoints := ProvideEtcdEndpoints(cfg)
	logger := ProvideLogger(cfg)
	repo, cleanup, err := membershipetcd.New(endpoints, logger)
	if err != nil {
		return nil, nil, err
	}
	return repo, func() {
		cleanup()
	}, nil
}

// container.go:

var _ entity.WALFactory = walFactory{}
