// Code generated by MockGen. DO NOT EDIT.
// Source: backend/queue/entity/repo-membership.go
//
// Generated by this command:
//
//	mockgen -source=backend/queue/entity/repo-membership.go -destination=backend/queue/mocks/mock_membership_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	gomock "go.uber.org/mock/gomock"
)

// MockMembershipRepo is a mock of MembershipRepo interface.
type MockMembershipRepo struct {
	ctrl     *gomock.Controller
	recorder *MockMembershipRepoMockRecorder
	isgomock struct{}
}

// MockMembershipRepoMockRecorder is the mock recorder for MockMembershipRepo.
type MockMembershipRepoMockRecorder struct {
	mock *MockMembershipRepo
}

// NewMockMembershipRepo creates a new mock instance.
func NewMockMembershipRepo(ctrl *gomock.Controller) *MockMembershipRepo {
	mock := &MockMembershipRepo{ctrl: ctrl}
	mock.recorder = &MockMembershipRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockMembershipRepo) EXPECT() *MockMembershipRepoMockRecorder {
	return m.recorder
}

// Close mocks base method.
func (m *MockMembershipRepo) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockMembershipRepoMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockMembershipRepo)(nil).Close))
}

// Register mocks base method.
func (m *MockMembershipRepo) Register(ctx context.Context, id, addr string, ttlSeconds int64) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Register", ctx, id, addr, ttlSeconds)
	ret0, _ := ret[0].(error)
	return ret0
}

// Register indicates an expected call of Register.
func (mr *MockMembershipRepoMockRecorder) Register(ctx, id, addr, ttlSeconds any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Register", reflect.TypeOf((*MockMembershipRepo)(nil).Register), ctx, id, addr, ttlSeconds)
}
