// Code generated by MockGen. DO NOT EDIT.
// Source: backend/queue/entity/repo-wal.go
//
// Generated by this command:
//
//	mockgen -source=backend/queue/entity/repo-wal.go -destination=backend/queue/mocks/mock_wal_repo.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	reflect "reflect"

	entity "github.com/harryv2/ryuk-dpq/backend/queue/entity"
	engine "github.com/harryv2/ryuk-dpq/backend/queue/logic/engine"
	gomock "go.uber.org/mock/gomock"
)

// MockWALRepo is a mock of WALRepo interface.
type MockWALRepo struct {
	ctrl     *gomock.Controller
	recorder *MockWALRepoMockRecorder
	isgomock struct{}
}

// MockWALRepoMockRecorder is the mock recorder for MockWALRepo.
type MockWALRepoMockRecorder struct {
	mock *MockWALRepo
}

// NewMockWALRepo creates a new mock instance.
func NewMockWALRepo(ctrl *gomock.Controller) *MockWALRepo {
	mock := &MockWALRepo{ctrl: ctrl}
	mock.recorder = &MockWALRepoMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWALRepo) EXPECT() *MockWALRepoMockRecorder {
	return m.recorder
}

// AppendAttempt mocks base method.
func (m *MockWALRepo) AppendAttempt(slot uint16, id string, attempts uint32, epoch uint64) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendAttempt", slot, id, attempts, epoch)
}

// AppendAttempt indicates an expected call of AppendAttempt.
func (mr *MockWALRepoMockRecorder) AppendAttempt(slot, id, attempts, epoch any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendAttempt", reflect.TypeOf((*MockWALRepo)(nil).AppendAttempt), slot, id, attempts, epoch)
}

// AppendEnqueue mocks base method.
func (m_2 *MockWALRepo) AppendEnqueue(slot uint16, m *engine.Message) error {
	m_2.ctrl.T.Helper()
	ret := m_2.ctrl.Call(m_2, "AppendEnqueue", slot, m)
	ret0, _ := ret[0].(error)
	return ret0
}

// AppendEnqueue indicates an expected call of AppendEnqueue.
func (mr *MockWALRepoMockRecorder) AppendEnqueue(slot, m any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendEnqueue", reflect.TypeOf((*MockWALRepo)(nil).AppendEnqueue), slot, m)
}

// AppendTerminal mocks base method.
func (m *MockWALRepo) AppendTerminal(slot uint16, id string, kind engine.TerminalKind) {
	m.ctrl.T.Helper()
	m.ctrl.Call(m, "AppendTerminal", slot, id, kind)
}

// AppendTerminal indicates an expected call of AppendTerminal.
func (mr *MockWALRepoMockRecorder) AppendTerminal(slot, id, kind any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "AppendTerminal", reflect.TypeOf((*MockWALRepo)(nil).AppendTerminal), slot, id, kind)
}

// Close mocks base method.
func (m *MockWALRepo) Close() error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Close")
	ret0, _ := ret[0].(error)
	return ret0
}

// Close indicates an expected call of Close.
func (mr *MockWALRepoMockRecorder) Close() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Close", reflect.TypeOf((*MockWALRepo)(nil).Close))
}

// Compact mocks base method.
func (m *MockWALRepo) Compact(slot uint16, msgs []*engine.Message) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Compact", slot, msgs)
	ret0, _ := ret[0].(error)
	return ret0
}

// Compact indicates an expected call of Compact.
func (mr *MockWALRepoMockRecorder) Compact(slot, msgs any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Compact", reflect.TypeOf((*MockWALRepo)(nil).Compact), slot, msgs)
}

// Drop mocks base method.
func (m *MockWALRepo) Drop(slot uint16) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Drop", slot)
	ret0, _ := ret[0].(error)
	return ret0
}

// Drop indicates an expected call of Drop.
func (mr *MockWALRepoMockRecorder) Drop(slot any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Drop", reflect.TypeOf((*MockWALRepo)(nil).Drop), slot)
}

// Incarnation mocks base method.
func (m *MockWALRepo) Incarnation() uint64 {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Incarnation")
	ret0, _ := ret[0].(uint64)
	return ret0
}

// Incarnation indicates an expected call of Incarnation.
func (mr *MockWALRepoMockRecorder) Incarnation() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Incarnation", reflect.TypeOf((*MockWALRepo)(nil).Incarnation))
}

// Replay mocks base method.
func (m *MockWALRepo) Replay() (map[uint16][]*engine.Message, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Replay")
	ret0, _ := ret[0].(map[uint16][]*engine.Message)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Replay indicates an expected call of Replay.
func (mr *MockWALRepoMockRecorder) Replay() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Replay", reflect.TypeOf((*MockWALRepo)(nil).Replay))
}

// MockWALFactory is a mock of WALFactory interface.
type MockWALFactory struct {
	ctrl     *gomock.Controller
	recorder *MockWALFactoryMockRecorder
	isgomock struct{}
}

// MockWALFactoryMockRecorder is the mock recorder for MockWALFactory.
type MockWALFactoryMockRecorder struct {
	mock *MockWALFactory
}

// NewMockWALFactory creates a new mock instance.
func NewMockWALFactory(ctrl *gomock.Controller) *MockWALFactory {
	mock := &MockWALFactory{ctrl: ctrl}
	mock.recorder = &MockWALFactoryMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *MockWALFactory) EXPECT() *MockWALFactoryMockRecorder {
	return m.recorder
}

// List mocks base method.
func (m *MockWALFactory) List() ([]engine.QueueKey, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "List")
	ret0, _ := ret[0].([]engine.QueueKey)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// List indicates an expected call of List.
func (mr *MockWALFactoryMockRecorder) List() *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "List", reflect.TypeOf((*MockWALFactory)(nil).List))
}

// Open mocks base method.
func (m *MockWALFactory) Open(key engine.QueueKey) (entity.WALRepo, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Open", key)
	ret0, _ := ret[0].(entity.WALRepo)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// Open indicates an expected call of Open.
func (mr *MockWALFactoryMockRecorder) Open(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Open", reflect.TypeOf((*MockWALFactory)(nil).Open), key)
}

// Remove mocks base method.
func (m *MockWALFactory) Remove(key engine.QueueKey) error {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "Remove", key)
	ret0, _ := ret[0].(error)
	return ret0
}

// Remove indicates an expected call of Remove.
func (mr *MockWALFactoryMockRecorder) Remove(key any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "Remove", reflect.TypeOf((*MockWALFactory)(nil).Remove), key)
}
